export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const UPDATE_NEW_COMMENT_TEXT = "UPDATE_NEW_COMMENT_TEXT";
export const UPDATE_AUTHOR_TEXT = "UPDATE_AUTHOR_TEXT";
export const SHOW_ALERT = "SHOW_ALERT";